# fly.toml app configuration file generated for ilokoodi-wagtail-portfolio on 2023-10-06T17:05:39+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ilokoodi-wagtail-portfolio"
primary_region = "arn"

[deploy]
    release_command = "/code/manage.py migrate"

[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
